version: '3.1'

services:
  db:
    image: postgres
    container_name: 'crackq_db'
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_DB=crackq
      - POSTGRES_PASSWORD=crackq
      - PGDATA=/var/lib/postgresql/data/pgdata

volumes:
  db-data:
